<?php 
 ini_set('max_execution_time', '0');
/*error_reporting(E_ALL);
ini_set('display_errors', 1);*/
$host = getenv('DB_HOST');
$user = getenv('DB_USER');
$password = getenv('DB_PASSWORD');
$dbUSPTO = getenv('DB_USPTO_DB');
$dbBusiness = getenv('DB_BUSINESS');
$dbApplication = getenv('DB_APPLICATION_DB');
$con = new mysqli($host, $user, $password, $dbApplication);

$variables = $argv;
//$variables = $_GET;
if(count($variables) == 3) {
	$organisationID = $variables[1];
	$representativeID = $variables[2];
	echo $organisationID;
	if((int)$organisationID > 0) {
		$queryOrganisation = 'SELECT * FROM db_business.organisation WHERE organisation_id ="'.$organisationID.'"';
		
		$resultOrganisation = $con->query($queryOrganisation);
		
		if($resultOrganisation && $resultOrganisation->num_rows > 0) {
			$orgRow = $resultOrganisation->fetch_object();
			
			$orgConnect = new mysqli($orgRow->org_host,$orgRow->org_usr,$orgRow->org_pass,$orgRow->org_db);
			
			if($orgConnect) {
				/*Check from client database */
				if($representativeID != "" && $representativeID > 0) {
					$queryRepresentative = "SELECT representative_id, representative_name,original_name FROM representative WHERE representative_id = '".$representativeID."' AND parent_id = 0";
				} else {
					$queryRepresentative = "SELECT representative_id, representative_name,original_name FROM representative WHERE parent_id = 0";
				}
				$resultRepresentativeParentCompany = $orgConnect->query($queryRepresentative);
		
				if($resultRepresentativeParentCompany && $resultRepresentativeParentCompany->num_rows > 0) {
					while($row = $resultRepresentativeParentCompany->fetch_object()){
						$nameRepresentaitve = $row->representative_name;
						if($nameRepresentaitve == null ) {
							$nameRepresentaitve = $row->original_name;
						}
						
						
						$findRepresentativeName = "Select representative_id, original_name, representative_name FROM representative WHERE representative_id = '".$row->representative_id."' OR parent_id = '".$row->representative_id."'";
						
						$resultRepresentativeCompanies = $orgConnect->query($findRepresentativeName);
						
						$allNames = array();
						while($rowRepresentative = $resultRepresentativeCompanies->fetch_object()){
							/*$name = $rowRepresentative->representative_name;
							if($name == null || $name == "") {
								
							}*/
							$name = $rowRepresentative->original_name;
							array_push($allNames, "'".$con->real_escape_string($name)."'");							
						}
						echo $orgRow->organisation_id.", ".$row->representative_id."<br/>";
						$con->query("DELETE FROM tree_parties WHERE organisation_id = ".$orgRow->organisation_id. " AND representative_id = ".$row->representative_id);
						$con->query("DELETE FROM tree_parties_collection WHERE organisation_id = ".$orgRow->organisation_id. " AND representative_id = ".$row->representative_id);
						
						$queryPurchase = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "0" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("assignment", "partialassignment") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $queryPurchase."<br/>";
						$con->query($queryPurchase);
						
						$querySale = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "1" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ac ON ac.rf_id = or.rf_id INNER JOIN documentid as d ON ac.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ac.convey_ty IN ("assignment", "partialassignment") AND ac.employer_assign = 0  AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name';
						echo $querySale."<br/>";
						$con->query($querySale);
						
						/*License-In*/
						$queryLicenseIn = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "2" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("license", "licenseend", "govern") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $queryLicenseIn."<br/>";
						$con->query($queryLicenseIn);
						
						/*License-Out*/
						$queryLicenseOut = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "3" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ac ON ac.rf_id = or.rf_id INNER JOIN documentid as d ON ac.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ac.convey_ty IN ("license", "licenseend", "govern") AND ac.employer_assign = 0  AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name';
						echo $queryLicenseOut."<br/>";
						$con->query($queryLicenseOut);
						
						/*SecurityOut*/
						$querySecurityOut = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "4" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("security", "restatedsecurity") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name';
						echo $querySecurityOut."<br/>";
						$con->query($querySecurityOut);
						
						/*ReleaseIn*/
						$queryReleaseIn = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "4" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as `ee` INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("release", "restatedsecurity") AND ass.employer_assign = 0 AND  (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name ';
						echo $queryReleaseIn."<br/>";
						$con->query($queryReleaseIn);
						
						/*MergerIn*/
						$queryMergerIn = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name,  "5" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name  FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "merger" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $queryMergerIn."<br/>";
						$con->query($queryMergerIn);
						
						/*MergerOut*/
						$queryMergerOut = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name,  "6" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name  FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "merger" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryMergerOut."<br/>";
						$con->query($queryMergerOut);
						
						/*Option*/
						$queryOptionIn = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name,  "7" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name  FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "option" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryOptionIn."<br/>";
						$con->query($queryOptionIn);
								
						$queryOptionOut = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "7" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "option" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $queryOptionOut."<br/>";
						$con->query($queryOptionOut);
						
						/*CourtOrders*/
						$queryCourtOrderIn = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "8" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name  FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "courtorder" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryCourtOrderIn."<br/>";
						$con->query($queryCourtOrderIn);
						
						$queryCourtOrderOut = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "8" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name  FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "courtorder" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $queryCourtOrderOut."<br/>";
						$con->query($queryCourtOrderOut);
						
						$customEmployeeQuery = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "9" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM db_uspto.assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.employer_assign = 1 AND ass.convey_ty IN ("assignment", "partialassignment", "employee") AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id GROUP BY show_name';
						echo $customEmployeeQuery."<br/>";						
						$con->query($customEmployeeQuery);
						
						/*Missing*/
						$queryMissingChange = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "missing" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name ';
						echo $queryMissingChange."<br/>";
						$con->query($queryMissingChange);
						
						$queryMissingChangeAssignor = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "missing" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryMissingChangeAssignor."<br/>";
						$con->query($queryMissingChangeAssignor);
						
						/*Other*/
						$queryOtherChange = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "other" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name ';
						echo $queryOtherChange."<br/>";
						$con->query($queryOtherChange);
						
						$queryOtherChangeAssignor = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "other" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryOtherChangeAssignor."<br/>";
						$con->query($queryOtherChangeAssignor);
						
						/*NameChange*/
						$queryNameChange = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "namechg" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id GROUP BY show_name ';
						echo $queryNameChange."<br/>";
						$con->query($queryNameChange);
						
						$queryNameChangeAssignor = 'INSERT IGNORE INTO tree_parties (assignor_and_assignee_id, name, tab_id, organisation_id, representative_id, representative_name) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, CASE WHEN r.representative_name IS NOT NULL THEN r.representative_name ELSE aaa.name END as show_name, "10" as tab, "'.$orgRow->organisation_id.'" as organisation_id, "'.$row->representative_id.'" as representative_id, "'.$con->real_escape_string($nameRepresentaitve).'" as representative_name FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "namechg" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id GROUP BY show_name ';
						echo $queryNameChangeAssignor."<br/>";
						$con->query($queryNameChangeAssignor);
						
						
						
						$queryPurchaseCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "0" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("assignment", "partialassignment") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id';
						echo $queryPurchaseCollectionsQuery."<br/>";
						$con->query($queryPurchaseCollectionsQuery);

						$querySaleCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "1" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ac ON ac.rf_id = or.rf_id INNER JOIN documentid as d ON ac.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ac.convey_ty IN ("assignment", "partialassignment") AND ac.employer_assign = 0  AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id';
						echo $querySaleCollectionsQuery."<br/>";
						$con->query($querySaleCollectionsQuery);	
						
						/*License-In*/
						$queryLicenseInCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "2" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("license", "licenseend", "govern") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id ';
						echo $queryLicenseInCollectionsQuery."<br/>";
						$con->query($queryLicenseInCollectionsQuery);
						
						/*License-Out*/
						$queryLicenseOutCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "3" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ac ON ac.rf_id = or.rf_id INNER JOIN documentid as d ON ac.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ac.convey_ty IN ("license", "licenseend", "govern") AND ac.employer_assign = 0  AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryLicenseOutCollectionsQuery."<br/>";
						$con->query($queryLicenseOutCollectionsQuery);
						
						/*SecurityOut*/
						$querySecurityOutCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "4" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("security", "restatedsecurity") AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $querySecurityOutCollectionsQuery."<br/>";
						$con->query($querySecurityOutCollectionsQuery);
						
						/*ReleaseIn*/
						$queryReleaseInCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id,or.rf_id, or.exec_dt, "4" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as `ee` INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty IN ("release", "restatedsecurity") AND ass.employer_assign = 0 AND  (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryReleaseInCollectionsQuery."<br/>";
						$con->query($queryReleaseInCollectionsQuery);
						
						
						/*MergerIn*/
						$queryMergerInCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "5" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "merger" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryMergerInCollectionsQuery."<br/>";
						$con->query($queryMergerInCollectionsQuery);
						
						
						/*MergerOut*/
						$queryMergerOutCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "6" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "merger" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryMergerOutCollectionsQuery."<br/>";
						$con->query($queryMergerOutCollectionsQuery);
						
						/*Option*/
						$queryOptionInCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "7" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id  FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "option" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id  ';
						echo $queryOptionInCollectionsQuery."<br/>";
						$con->query($queryOptionInCollectionsQuery);
						
						$queryOptionOutCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "7" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "option" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryOptionOutCollectionsQuery."<br/>";
						$con->query($queryOptionOutCollectionsQuery);
						
						
						/*CourtOrders*/
						$queryCourtOrderInCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "8" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as ee LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "courtorder" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryCourtOrderInCollectionsQuery."<br/>";
						$con->query($queryCourtOrderInCollectionsQuery);
						
						$queryCourtOrderOutCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "8" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "courtorder" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryCourtOrderOutCollectionsQuery."<br/>";
						$con->query($queryCourtOrderOutCollectionsQuery);
						
						$customEmployeeQueryCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "9" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM db_uspto.assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.employer_assign = 1 AND ass.convey_ty IN ("assignment", "partialassignment", "employee") AND (aa.name IN ('.implode(",",$allNames).'))) as temp ON temp.rf_id = or.rf_id ';
						echo $customEmployeeQueryCollectionsQuery."<br/>";						
						$con->query($customEmployeeQueryCollectionsQuery);
						
						/*Missing*/
						$queryMissingChangeCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "missing" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryMissingChangeCollectionsQuery."<br/>";
						$con->query($queryMissingChangeCollectionsQuery);
						
						$queryMissingChangeAssignorCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "missing" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).')) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryMissingChangeAssignorCollectionsQuery."<br/>";
						$con->query($queryMissingChangeAssignorCollectionsQuery);
						
						/*Other*/
						$queryOtherChangeCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "other" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id  ';
						echo $queryOtherChangeCollectionsQuery."<br/>";
						$con->query($queryOtherChangeCollectionsQuery);
						
						$queryOtherChangeAssignorCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "other" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryOtherChangeAssignorCollectionsQuery."<br/>";
						$con->query($queryOtherChangeAssignorCollectionsQuery);
						
						/*NameChange*/
						$queryNameChangeCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, or.rf_id, or.exec_dt, "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignor as `or` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT ee.rf_id FROM assignee as ee INNER JOIN assignment_conveyance as ass ON ass.rf_id = ee.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "namechg" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY ee.rf_id) as temp ON temp.rf_id = or.rf_id ';
						echo $queryNameChangeCollectionsQuery."<br/>";
						$con->query($queryNameChangeCollectionsQuery);
						
						$queryNameChangeAssignorCollectionsQuery = 'INSERT IGNORE INTO tree_parties_collection (assignor_and_assignee_id, rf_id, exec_dt, tab_id, representative_id, organisation_id) SELECT aaa.assignor_and_assignee_id as assignor_and_assignee_id, ee.rf_id,(SELECT exec_dt FROM assignor where rf_id = ee.rf_id GROUP BY rf_id), "10" as tab, "'.$row->representative_id.'" as representative_id, "'.$orgRow->organisation_id.'" as organisation_id FROM assignee as `ee` LEFT JOIN assignor_and_assignee as aaa ON aaa.assignor_and_assignee_id = ee.assignor_and_assignee_id LEFT JOIN representative as r ON r.representative_id = aaa.representative_id INNER JOIN (SELECT or.rf_id FROM assignor as `or` INNER JOIN assignment_conveyance as ass ON ass.rf_id = or.rf_id INNER JOIN documentid as d ON ass.rf_id = d.rf_id INNER JOIN  assignor_and_assignee as aa ON aa.assignor_and_assignee_id = or.assignor_and_assignee_id LEFT JOIN representative as r1 ON r1.representative_id = aa.representative_id WHERE ass.convey_ty = "namechg" AND ass.employer_assign = 0 AND (aa.name IN ('.implode(",",$allNames).') ) GROUP BY or.rf_id) as temp ON temp.rf_id = ee.rf_id ';
						echo $queryNameChangeAssignorCollectionsQuery."<br/>";
						$con->query($queryNameChangeAssignorCollectionsQuery);
					}
				}
			}
		}
	}
}